BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LESSONS ADD START_SEC NUMBER(6)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LESSONS ADD END_SEC NUMBER(6)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN
      RAISE;
    END IF;
END;
/

UPDATE LESSONS SET START_SEC = 0, END_SEC = 117 WHERE COURSE_ID = 11 AND ORDER_NO = 1;
UPDATE LESSONS SET START_SEC = 117, END_SEC = 234 WHERE COURSE_ID = 11 AND ORDER_NO = 2;
UPDATE LESSONS SET START_SEC = 234, END_SEC = 351 WHERE COURSE_ID = 11 AND ORDER_NO = 3;
UPDATE LESSONS SET START_SEC = 351, END_SEC = 468 WHERE COURSE_ID = 11 AND ORDER_NO = 4;
UPDATE LESSONS SET START_SEC = 468, END_SEC = 585 WHERE COURSE_ID = 11 AND ORDER_NO = 5;
UPDATE LESSONS SET START_SEC = 585, END_SEC = 702 WHERE COURSE_ID = 11 AND ORDER_NO = 6;
UPDATE LESSONS SET START_SEC = 702, END_SEC = 820 WHERE COURSE_ID = 11 AND ORDER_NO = 7;
